on: push
    
jobs:
    backup:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - run: |
              git pull --unshallow
              echo '${{secrets.KEY}}' > key
              chmod 400 key
              git -c core.sshCommand='ssh -i key -o StrictHostKeyChecking=no' push -f git@bitbucket.org:chaowenguo/${GITHUB_REPOSITORY#*/}
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
        - uses: actions/checkout@main
        - uses: actions/setup-java@main
          with:
              java-version: 18
              distribution: zulu
        - run: curl https://bitbucket.org/chaowenguo/common/raw/main/version.jsh | jshell -
        - uses: actions/setup-java@main
          with:
              java-version: ${{env.JAVA}}
              distribution: zulu
        - run: |
              echo '${{secrets.KEY}}' > key
              chmod 400 key
              ips=$(curl https://bitbucket.org/chaowenguo/server/raw/main/ip.json | sed -e s/,/\ /g -e s/[][\"]//g)
              array=($ips)
              ssh -o StrictHostKeyChecking=no -i key ubuntu@${array[3]} 'sudo docker stop $(sudo docker container ls -q)
              sudo docker system prune -af
              sudo rm -rf /var/lib/cockroach
              sudo docker network create backend
              sudo docker run -d --name cockroach --net backend -p 26257:26257 -v ~/certs:/certs:ro -v /var/lib/cockroach/data:/cockroach/cockroach-data --restart always cockroachdb/cockroach start --certs-dir /certs --advertise-addr $(curl https://ifconfig.me) --join $(echo '$ips' | sed s/\ /,/g)
              sudo docker run -d --name redis --net backend -p 6379:6379 -p 16379:16379 redis --cluster-enabled yes --masterauth ${{secrets.PASSWORD}} --requirepass ${{secrets.PASSWORD}}'
    clean:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - uses: actions/setup-python@main
          with:
              python-version: 3.x
        - run: |
              pip install aiohttp
              curl https://bitbucket.org/chaowenguo/common/raw/main/clean.py | python - ${{secrets.GITHUB_TOKEN}}
